server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/sk_local
    username: postgres
    password: root
  mail:
    host: smtp.gmail.com
    username: sanofkaz@gmail.com
    password: Dusseldorf!2020
    port: 465
    protocol: smtps
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.xml
  servlet:
    multipart:
      max-file-size: 2MB

mail:
  host: localhost
  port: 1025
  username: hello
  password: hello
  debug: true

twilio:
  account_sid: AC8e6fe899b4538ff6af5d16b2350858b6
  auth_token: af3413216cca168c68691012420ac76a
  trial_number: +14845754250

security:
  account:
    confirm:
      link: http://localhost:8080/auth/confirm-account?tokenId="
  token:
    secret: SECRET

notification:
  params:
    keys:
      phone-number-from: phoneNumberFrom
      phone-number-to: phoneNumberTo
      email-from: emailFrom
      email-to: emailTo
  error:
    template:
      not-valid: Notification Template is not valid
    params:
      not-valid: Notification Template params are not valid

logging:
  file:
#    path: C:\Users\Mi Notebook\Desktop\sankaz-config
    name: app.log

application:
  rest:
    response:
      success: success
      error: error
  file:
    upload:
      path:
        image: D:/var/www/content/sankaz/images/
    download:
      path:
        image: D:/var/www/content/sankaz/images/