server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    #    url: jdbc:postgresql://localhost:5439/sankaz_doc
    #    username: postgres
    #    password: root
    url: jdbc:postgresql://localhost:5432/sankaz_loc
    username: postgres
    password: root
  #    url: jdbc:postgresql://185.146.1.64:5432/sankaz_dev
  #    username: sankaz
  #    password: sankaz
  #    url: jdbc:postgresql://185.146.1.64:5432/sankaz_admin_dev
  #    username: sankaz
  #    password: sankaz
  mail:
    host: smtp.gmail.com
    username: sanofkaz@gmail.com
    password: Dusseldorf!2020
    port: 465
    protocol: smtps
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 7MB

mail:
  host: localhost
  port: 1025
  username: hello
  password: hello
  debug: true

twilio:
  account_sid: AC8e6fe899b4538ff6af5d16b2350858b6
  auth_token: af3413216cca168c68691012420ac76a
  trial_number: +14845754250

security:
  account:
    confirm:
      link: http://localhost:8080/auth/confirm-account?tokenId="
  token:
    secret: SECRET

notification:
  params:
    keys:
      phone-number-from: phoneNumberFrom
      phone-number-to: phoneNumberTo
      email-from: emailFrom
      email-to: emailTo
  error:
    template:
      not-valid: Notification Template is not valid
    params:
      not-valid: Notification Template params are not valid

logging:
  file:
    #    path: C:\Users\Mi Notebook\Desktop\sankaz-config
    name: app.log

application:
  url:
    base: http://localhost:8080
  rest:
    response:
      success: success
      error: error
  file:
    upload:
      path:
        image: /Users/almatrakhmetolla/IdeaProjects/sankaz
    download:
      path:
        image: /Users/almatrakhmetolla/IdeaProjects/sankaz
fcm:
  service-account-file: sankaz-push-firebase-adminsdk.json
payment:
  model:
    prefix: sankaz_loc_
  api:
    base-url: https://api.yii2-stage.test.wooppay.com/v1
  operation:
    create: /invoice/create
    auth: /auth
  merchant:
    login: merchViktor
    password: A12345678a
  test-user:
    card-number: 4111111111111111
    card-exp: 09/25
    card-cvv: 653
  expires:
    min: 10